### ISSUE TITLE
[GSoC Project Proposal]: Google Earth Ocean Python Package 

### ISSUE THREAD

**Issue by mphemming** [ioos/gsoc#47]
### Project Description

With the rapid increase of geospatial oceanographic data collection over the last decade, there is a need to visualise data fast and easily. One method is to import such data sets into Google Earth, allowing for interactive data exploration. However, presently most oceanographic data sets cannot be opened this way. Therefore, we wish to develop a python package that converts geospatial oceanographic data sets to suitable formats that can be imported and visualised using Google Earth quickly and easily.  

### Expected Outcomes

Public release of a python package that converts geospatial oceanographic data sets to Google Earth formats for quick visualization and analysis. The intern will gain knowledge in python package development, and will become familiar with geospatial oceanographic data sets.  

### Skills required

Python, Git 

### Mentor(s)

@mphemming, @moninya

### Expected Project Size

175

### What is the difficulty of the project?

Intermediate

**Comment by mwengren** [comment]
@mphemming Thank you for your project idea contribution to IOOS' GSoC application.  

Unfortunately, GSoC is targeted towards existing open source software projects that have an established code base and active developer community, rather than ideas for new projects or packages.  More information about this can be found in this [public GSoC slide deck](https://docs.google.com/presentation/d/1YTOJEJwGjAWW4DKEuK2xWf36y8EIkauUZMZu8k68E74/edit#slide=id.g2ae078c3ccb_0_21) that describes the expectations for organizations looking to apply.

I'd recommend getting this project idea going on your own and consider re-submitting it next year once there is a public code base available.
