### ISSUE TITLE
[GSoC Project Proposal]: Take ocean auto-reporting to the cloud 

### ISSUE THREAD

**Issue by mphemming** [ioos/gsoc#48]
### Project Description

With the rapid increase in collection and dissemination of ocean data the use of automated data processing and reporting is gaining popularity. Reports are currently generated manually and locally, however to create fully automated reports the use of cloud services is required. The intern will work on migrating and adapting existing python code used for data reporting, so that reports are generated automatically when new oceanographic data sets are added to the repository.  

### Expected Outcomes

Migration of oceanographic data set auto-reporting scripts to the cloud, and automatic report creation. The intern will gain knowledge in python, cloud services, and various ocean data sets.  

### Skills required

Python, Git 

### Mentor(s)

@mphemming, @moninya

### Expected Project Size

175

### What is the difficulty of the project?

Intermediate

**Comment by mwengren** [comment]
@mphemming Thank you for your project idea contribution to IOOS' GSoC application.  

Unfortunately, GSoC is targeted towards existing open source software projects that have an established code base and active developer community, rather than ideas for new projects or packages.  More information about this can be found in this [public GSoC slide deck](https://docs.google.com/presentation/d/1YTOJEJwGjAWW4DKEuK2xWf36y8EIkauUZMZu8k68E74/edit#slide=id.g2ae078c3ccb_0_21) that describes the expectations for organizations looking to apply.

I'd recommend getting this project idea going on your own and consider re-submitting it next year once there is a public code base available.

**Comment by 7yl4r** [comment]
Perhaps this idea can be modified to use existing tools like quarto + github actions? That stack is how our best Marinebon reports are made.

**Comment by mphemming** [comment]
thanks for the suggestion. We have already created a python package using LaTeX, so will investigate whether we can use github actions with the existing code.
